### ISSUE TITLE
Write an ETL script to process archived Zenodo records

### ISSUE THREAD

**Issue by e-belfer** [catalyst-cooperative/pudl-usage-metrics#181]
The archiver in #177 already combines metadata for all records into one table, so the process of ETL'ing this data should be quite minimal. We need to:

- `raw_`: extract the csv into a Pandas dataframe
- `core_`: handle any column renaming, minor cleanup
```[tasklist]
### Tasks
- [x] Update archiver to grab version and publication date
- [x] Extract raw table
- [x] Transform to core table
- [x] Add alembic migration and write to SQL db's
```
